version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: hospital-management_postgres
    environment:
      POSTGRES_DB: hospital-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: hospital-management_v1
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - hospital_management-net

  app:
    build: .
    container_name: hospital-management_app
    depends_on:
      - db
    ports:
      - "8180:8180"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/hospital-db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: hospital-management_v1
      SPRING_JPA_HIBERNATE_DDL_AUTO: validate
      SPRING_FLYWAY_ENABLED: "true"
      SPRING_FLYWAY_BASELINE_ON_MIGRATE: "true"
      SERVER_PORT: 8180
    networks:
      - hospital_management-net

volumes:
  postgres_data:

networks:
  hospital_management-net:
